### ISSUE TITLE
Unable to perform Artsy oauth2 sign-in

### ISSUE THREAD

**Issue by alloy** [alloy/anthology#4]
The code is on this branch: https://github.com/alloy/anthology/tree/stash-auth

When running locally, I get:

```
OAuth2::Error (Unauthorized: 
{"error":"Unauthorized","text":"The access token is invalid or has expired."}):
  oauth2 (1.0.0) lib/oauth2/client.rb:114:in `request'
  oauth2 (1.0.0) lib/oauth2/access_token.rb:107:in `request'
  oauth2 (1.0.0) lib/oauth2/access_token.rb:114:in `get'
  /Users/eloy/.gem/bundler/gems/omniauth-artsy-663d6fc8511e/lib/omniauth/strategies/artsy.rb:24:in `raw_info'
  /Users/eloy/.gem/bundler/gems/omniauth-artsy-663d6fc8511e/lib/omniauth/strategies/artsy.rb:16:in `block in <class:Artsy>'
  omniauth (1.2.2) lib/omniauth/strategy.rb:105:in `instance_eval'
  omniauth (1.2.2) lib/omniauth/strategy.rb:105:in `block in compile_stack'
  omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `each'
  omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `inject'
  omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `compile_stack'
  (eval):7:in `uid_stack'
  omniauth (1.2.2) lib/omniauth/strategy.rb:317:in `uid'
  omniauth (1.2.2) lib/omniauth/strategy.rb:333:in `auth_hash'
  omniauth (1.2.2) lib/omniauth/strategy.rb:361:in `callback_phase'
  omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
```

On the deployed version it redirects to http://artsy-anthology.herokuapp.com/auth/failure?message=invalid_credentials&strategy=artsy.

**Comment by alloy** [comment]
As per @dylanfareed’s advice, I had to go into Gravity and update the ‘app’ to use API v1 instead of v2.
